const assert = require('node:assert/strict')
const test = require('node:test')
const {
  electronPublicUpdateFeed,
  isSquirrelInstall,
  releaseVersion,
  squirrelAppUserModelId,
  squirrelUpdateExecutable,
} = require('../electron/updater-adapter.cjs')

test('builds the official Electron public update feed', () => {
  assert.equal(
    electronPublicUpdateFeed('v1.2.0', 'win32', 'x64'),
    'https://update.electronjs.org/lihongyao517/Hoya_agent/win32-x64/1.2.0',
  )
  assert.throws(() => electronPublicUpdateFeed('not-a-version', 'win32', 'x64'))
})

test('matches the AppUserModelID generated by Squirrel shortcuts', () => {
  assert.equal(squirrelAppUserModelId(), 'com.squirrel.HoyaAgent.Hoya Agent')
})

test('detects Squirrel installs without treating NSIS paths as Squirrel', () => {
  const squirrelExe = String.raw`C:\Users\demo\AppData\Local\HoyaAgent\app-1.2.0\Hoya Agent.exe`
  const nsisExe = String.raw`C:\Users\demo\AppData\Local\Programs\HoyaAgent\Hoya Agent.exe`
  assert.equal(
    squirrelUpdateExecutable(squirrelExe),
    String.raw`C:\Users\demo\AppData\Local\HoyaAgent\Update.exe`,
  )
  assert.equal(isSquirrelInstall(squirrelExe, (value) => value.endsWith('Update.exe')), true)
  assert.equal(isSquirrelInstall(nsisExe, () => true), false)
})

test('normalizes updater event versions', () => {
  assert.equal(releaseVersion({ version: '1.2.0' }, '', '1.1.2'), '1.2.0')
  assert.equal(releaseVersion({}, 'Hoya Agent v1.3.0', '1.1.2'), '1.3.0')
  assert.equal(releaseVersion({}, '', '1.1.2'), '1.1.2')
})
